### ISSUE TITLE
How to quantify transferable elements

### ISSUE THREAD

**Issue by zhangwenda0518** [boulardlab/3t-seq#7]
Hello ，thank you for developing such a convenient tool
One question is, when I want to quantify transferable elements, what data should I input, second-generation DNA sequencing or RNA transcriptome data?
I currently see that it seems to be inputting RNA transcriptome data. There is no doubt that transcriptome alignment is based on genes. How is it possible to achieve quantitative analysis of transferable elements？

Thanks！

**Comment by ftabaro** [comment]
Hello, 

the 3t-seq pipeline uses transcriptomic data to quantify transposable elements expression. 

It implements three ways to assess it: two use the STAR aligner with different combination of parameters, the other one uses a reference-free method called SalmonTE (which, in turn, uses Salmon). For SalmonTE and the so-called "STAR-TE random" method we deliver also reports on differentially expressed transposable elements between two conditions.

**Comment by zhangwenda0518** [comment]
ok ,Thanks, I will try it on my data!
